### ISSUE TITLE
Registro de Ferramenta

### ISSUE THREAD

**Issue by Shoto29** [chrislcontrol/tool-rental#41]
Local: Tela de registro de ferramenta.
Bug: Não aceita valor de ferramenta no formato 100,0 somente valores separados por "."

**Comment by FrancescoGhisi** [comment]
Esse link: https://stackoverflow.com/questions/4323599/best-way-to-parsedouble-with-comma-as-decimal-separator
Talvez possa ajudar fix esse bug

**Comment by vinigoulartalves** [comment]
Feito as alterações no RegisterToolFrame.java
